config/routes.rb
Rails.application.routes.draw do
  resources :purchases
  resources :products do
    post "buy", on: :member
  end
  post "/webhook", to: "products#webhook"
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  root "products#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :seller, class_name: "User"
  has_many :purchases, dependent: :destroy
  has_many :buyers, through: :purchases, class_name: "User"
end

app/models/purchase.rb
class Purchase < ApplicationRecord
  belongs_to :product
  belongs_to :buyer, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # Seller
  has_many :products, foreign_key: :seller_id, dependent: :destroy
  # Buyer
  has_many :purchases, foreign_key: :buyer_id, dependent: :destroy

  def has_purchased?(product)
    purchases.where(product_id: product.id).any?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: %i[ show buy ]
  before_action :set_seller_product, only: %i[ edit update destroy ]
  before_action :authenticate_user!, only: %i[ new create edit update destroy buy ]

  protect_from_forgery except: :webhook

  # GET /products or /products.json
  def index
    @products = Product.all
  end

  # GET /products/1 or /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = current_user.products.new
  end

  def buy
    session = Stripe::Checkout::Session.create({
      client_reference_id: @product.id,
      line_items: [{
        price: 'price_1QVG83G5j8M59D7ef0A8G1lH',
        quantity: 1,
      }],
      customer_email: current_user&.email,
      mode: 'payment',
      success_url: product_url(@product),
      cancel_url: product_url(@product),
    })

    redirect_to session.url, status: 303, allow_other_host: true
  end

  def webhook
    event = nil

    begin
      sig_header = request.env['HTTP_STRIPE_SIGNATURE']
      payload = request.body.read
      event = Stripe::Webhook.construct_event(payload, sig_header, ENV['STRIPE_WEBHOOK_ENDPOINT_SECRET'])
    rescue JSON::ParserError => e
      render json: { status: 400, error: e.message } and return
    rescue Stripe::SignatureVerificationError => e
      render json: { status: 400, error: e.message } and return
    end

    if event['type'] == 'checkout.session.completed'
      customer_email = event.data.object.customer_email
      product_id = event.data.object.client_reference_id

      customer = User.find_by(email: customer_email)
      purchase = customer.purchases.create(product_id: product_id)
    end

    render json: { status: 200 }
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products or /products.json
  def create
    @product = current_user.products.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: "Product was successfully created." }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1 or /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: "Product was successfully updated." }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1 or /products/1.json
  def destroy
    @product.destroy!

    respond_to do |format|
      format.html { redirect_to products_path, status: :see_other, notice: "Product was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    def set_seller_product
      @product = current_user.products.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      redirect_to :root, alert: "You are not authorized to edit this product." and return
    end

    def set_product
      @product = Product.find(params[:id])
    end

    def product_params
      params.require(:product).permit(:title, :description, :price, :seller_id)
    end
end

app/controllers/purchases_controller.rb
class PurchasesController < ApplicationController
  before_action :set_purchase, only: %i[ show edit update destroy ]

  # GET /purchases or /purchases.json
  def index
    @purchases = Purchase.all
  end

  # GET /purchases/1 or /purchases/1.json
  def show
  end

  # GET /purchases/new
  def new
    @purchase = Purchase.new
  end

  # GET /purchases/1/edit
  def edit
  end

  # POST /purchases or /purchases.json
  def create
    @purchase = Purchase.new(purchase_params)

    respond_to do |format|
      if @purchase.save
        format.html { redirect_to @purchase, notice: "Purchase was successfully created." }
        format.json { render :show, status: :created, location: @purchase }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @purchase.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /purchases/1 or /purchases/1.json
  def update
    respond_to do |format|
      if @purchase.update(purchase_params)
        format.html { redirect_to @purchase, notice: "Purchase was successfully updated." }
        format.json { render :show, status: :ok, location: @purchase }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @purchase.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /purchases/1 or /purchases/1.json
  def destroy
    @purchase.destroy!

    respond_to do |format|
      format.html { redirect_to purchases_path, status: :see_other, notice: "Purchase was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_purchase
      @purchase = Purchase.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def purchase_params
      params.fetch(:purchase, {})
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/purchases_helper.rb
module PurchasesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Minishop</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="mx-auto px-10 max-w-7xl">
    <header class="border-b border-palette-lighter sticky top-0 z-20 bg-white">
      <div class="flex items-center justify-between mx-auto max-w-6xl pb-2 pt-4 md:pt-6">
        <a class=" cursor-pointer" href="/">
          <h1 class="flex no-underline">
            <span class="text-xl font-primary font-bold tracking-tight pt-1">Minishop</span>
          </h1>
        </a>
        <div>
          <% if user_signed_in? %>
            <%= current_user.email %>
            <%= link_to "Sign out", destroy_user_session_path, data: { turbo_method: :delete } %>
          <% else %>
            <%= link_to "Sign up", new_user_registration_path %>
            <%= link_to "Sign in", new_user_session_path %>
          <% end %>
        </div>
      </div>
    </header>

    <main>
      <div class="mx-auto max-w-6xl py-12 mx-auto">
        <div class="">
          <p class="notice"><%= notice %></p>
          <p class="alert"><%= alert %></p>
        </div>
        <%= yield %>
      </div>
    </main>
  </body>
</html>

app/views/products/_form.html.erb
<%= form_with(model: product) do |form| %>
  <% if product.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
        <% product.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mt-6 grid grid-cols-1 gap-y-6 gap-x-4 sm:grid-cols-6">
    <div class="sm:col-span-6">
      <%= form.label :title, class: "block text-sm font-medium text-gray-700" %>
      <div class="mt-1">
        <%= form.text_field :title, label: false, class: "shadow-sm focus:ring-blue-500 focus:border-blue-500 block w-full border-gray-300 rounded-md" %>
      </div>
    </div>

    <div class="sm:col-span-6">
      <%= form.label :description, class: "block text-sm font-medium text-gray-700" %>
      <div class="mt-1">
        <%= form.text_area :description, class: "shadow-sm focus:ring-blue-500 focus:border-blue-500 block w-full border-gray-300 rounded-md" %>
      </div>
    </div>

    <div class="sm:col-span-6">
      <%= form.label :price, class: "block text-sm font-medium text-gray-700" %>
      <div class="mt-1 flex rounded-md shadow-sm">
        <span class="inline-flex items-center px-3 rounded-l-md border border-r-0 border-gray-300 bg-gray-50 text-gray-500 sm:text-sm">£</span>

        <%= form.text_field :price, class: "flex-1 focus:ring-blue-500 focus:border-blue-500 block w-full min-w-0 rounded-none rounded-r-md border-gray-300" %>
      </div>
    </div>

    <div class="sm:col-span-6">
      <%= form.submit class: "button" %>
    </div>
  </div>
<% end %>

app/views/products/_product.html.erb
<div class="min-h-screen py-12 sm:pt-20">
  <div class="flex flex-col justify-center items-center md:flex-row md:items-start space-y-8 md:space-y-0 md:space-x-4 lg:space-x-8 max-w-6xl w-11/12 mx-auto">
    <div class="w-full md:w-1/2 max-w-md border border-palette-lighter bg-white rounded shadow-lg">
      <div class="relative h-96">
        <div style="display: block; overflow: hidden; position: absolute; inset: 0px; box-sizing: border-box; margin: 0px;">
          <%= image_tag "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3f/Placeholder_view_vector.svg/1362px-Placeholder_view_vector.svg.png?20220519031949", id: "displayed-image", class: "transform duration-500 ease-in-out hover:scale-110", style:"position:absolute;top:0;left:0;bottom:0;right:0;box-sizing:border-box;padding:0;border:none;margin:auto;display:block;width:0;height:0;min-width:100%;max-width:100%;min-height:100%;max-height:100%" %>
        </div>
      </div>
      <div class="relative flex border-t border-palette-lighter">
        <div class="flex space-x-1 w-full overflow-auto border-t border-palette-lighter" style="scroll-behavior: smooth;">
            <% 4.times do%>
              <button class="relative w-40 h-32 flex-shrink-0 rounded-sm ">
                <div style="display: block; overflow: hidden; position: absolute; inset: 0px; box-sizing: border-box; margin: 0px;">
                      <%= image_tag "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3f/Placeholder_view_vector.svg/1362px-Placeholder_view_vector.svg.png?20220519031949", class: "thumbnail" %>
                </div>
              </button>
            <% end %>
        </div>
      </div>
    </div>
    <div class="flex flex-col justify-between h-full w-full md:w-1/2 max-w-xs mx-auto space-y-4 min-h-128">
      <div class=" font-primary">
        <h1 class="leading-relaxed font-extrabold text-3xl text-palette-primary py-2 sm:py-4">
          <%= product.title %>
        </h1>
        <p class="font-medium text-lg">
          <%= product.description %>
        </p>
        <div class="text-xl text-palette-primary font-medium py-4 px-1">
          $<span class="text-2xl"><%= product.price %>
          </span>
        </div>
      </div>


      <% if current_user&.has_purchased?(product) %>
        <p>You already own this product!</p>
      <% else %>
        <div class="w-full">
          <%= form_with model: product, url: buy_product_path(product), method: :post do %>
            <%= submit_tag "Buy now", data: { turbo: false }, class: "pt-3 pb-2 bg-palette-primary text-white w-full mt-2 rounded-sm font-primary font-semibold text-xl flex justify-center items-baseline  hover:bg-palette-dar k cursor-pointer", "aria-label": "cart-button" %>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/products/edit.html.erb
<% content_for :title, "Editing product" %>

<h1>Editing product</h1>

<%= render "form", product: @product %>

<br>

<div>
  <%= link_to "Show this product", @product %> |
  <%= link_to "Back to products", products_path %>
</div>

app/views/products/index.html.erb
<% if user_signed_in? %>
  <div class="text-right">
    <%= link_to "Add new product", new_product_path, class: "button" %>
  </div>
<% end %>

<div id="products" class="py-12 max-w-6xl mx-auto grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-x-4 gap-y-8">
  <% @products.each do |product| %>
    <%= link_to product, class:"h-120 w-72 overflow-hidden rounded-lg shadow-lg mx-auto border border-palette-lighter" do %>
      <div class="h-48 border-b-2 border-palette-lighter relative">
        <div style="display: block; overflow: hidden; position: absolute; inset: 0px; box-sizing: border-box; margin: 0px;">
          <%= image_tag "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3f/Placeholder_view_vector.svg/1362px-Placeholder_view_vector.svg.png?20220519031949", class: "transform duration-500 ease-in-out hover:scale-110"  %>
        </div>
      </div>
      <div class="h-48 relative">
        <div class="font-primary text-palette-primary text-2xl pt-4 px-4 font-semibold">
          <%= product.title %>
        </div>
        <div class="text-palette-dark font-primary font-medium text-base absolute bottom-0 right-0 mb-4 pl-8 pr-4 pb-1 pt-2 bg-palette-lighter  rounded-tl-sm triangle">
          $<span class="text-lg"><%= product.price %></span>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/products/new.html.erb
<h1 class="text-2xl my-4">Add a new product</h1>

<%= render "form", product: @product %>

app/views/products/show.html.erb
<div>
  <% if @product.seller == current_user %>
    <%= link_to "Edit this product", edit_product_path(@product), class: "underline" %>
  <% end %>
</div>

<%= render @product %>

app/views/purchases/_form.html.erb
<%= form_with(model: purchase) do |form| %>
  <% if purchase.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(purchase.errors.count, "error") %> prohibited this purchase from being saved:</h2>

      <ul>
        <% purchase.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/purchases/_purchase.html.erb
<div id="<%= dom_id purchase %>">
</div>

app/views/purchases/edit.html.erb
<% content_for :title, "Editing purchase" %>

<h1>Editing purchase</h1>

<%= render "form", purchase: @purchase %>

<br>

<div>
  <%= link_to "Show this purchase", @purchase %> |
  <%= link_to "Back to purchases", purchases_path %>
</div>

app/views/purchases/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Purchases" %>

<h1>Purchases</h1>

<div id="purchases">
  <% @purchases.each do |purchase| %>
    <%= render purchase %>
    <p>
      <%= link_to "Show this purchase", purchase %>
    </p>
  <% end %>
</div>

<%= link_to "New purchase", new_purchase_path %>

app/views/purchases/new.html.erb
<% content_for :title, "New purchase" %>

<h1>New purchase</h1>

<%= render "form", purchase: @purchase %>

<br>

<div>
  <%= link_to "Back to purchases", purchases_path %>
</div>

app/views/purchases/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @purchase %>

<div>
  <%= link_to "Edit this purchase", edit_purchase_path(@purchase) %> |
  <%= link_to "Back to purchases", purchases_path %>

  <%= button_to "Destroy this purchase", @purchase, method: :delete %>
</div>